version: "3"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nextjs
      - nestjs
    restart: on-failure:5

  nextjs:
    build: ../iek-admin-next
    container_name: nextjs
    restart: on-failure:5

  nestjs:
    build: .
    container_name: nestjs
    volumes:
      - ./public/uploads/images:/app/public/uploads/images
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure:5

  mysql:
    build: ./db
    container_name: mysql
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'iek_mysql'
      MYSQL_USER: 'iek_docker'
      MYSQL_PASSWORD: 'iek_docker_!@#10'
      MYSQL_ROOT_PASSWORD: 'root!@#10'
      TZ: 'Asia/Ulaanbaatar'
    ports:
      - 3310:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "--host=127.0.0.1", "--user=$MYSQL_USER", "--password=$MYSQL_PASSWORD"]
      timeout: 20s
      retries: 10
    restart: on-failure:5